module.exports = {
  arrowParens: "always",
  bracketSpacing: true,
  endOfLine: "lf",
  htmlWhitespaceSensitivity: "ignore",
  insertPragma: false,
  singleAttributePerLine: false,
  bracketSameLine: false,
  jsxBracketSameLine: true,
  jsxSingleQuote: true,
  printWidth: 80,
  proseWrap: "preserve",
  quoteProps: "as-needed",
  requirePragma: false,
  semi: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: "none",
  useTabs: true,
  vueIndentScriptAndStyle: false,
  filepath: "/Users/leejinw/Documents/codes/ljw/project/project--portfolio--nextjs/.prettierrc",
  parser: "yaml",
  rangeEnd: 44,
  rangeStart: 17,
  plugins: [require('prettier-plugin-tailwindcss')],
  tailwindConfig : "./tailwind.config.js"
}